### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by arijit79** [arijit79/minus#16]
The current testing module is broken. Could you please fix it @poliorcetics , since I am currently working on refinement for the next major version. I would be really thankful to you

**Comment by poliorcetics** [comment]
https://github.com/arijit79/minus/blob/fe06591d07fa2bad3257c8b323650beae78e411e/src/utils.rs#L189

This is what broke the tests, you added a parameter. Maybe there are other things, I didn't look too far.

You should run them locally before pushing. If you don't want to remember the exact commands, I recommend creating a branch an making a PR against your own repo. Not only will it make it easier for you to find bugs since CI will prevent merging it it fails, but also for eventual reviewers to help with `minus`, which is very hard actually since you are pushing directly on `master`.

I don't have the time to help before at least a week, probably more, sorry.

**Comment by arijit79** [comment]
No, there are more breaking changes. I am gonna fix them later. Thanks
