### ISSUE TITLE
Starting at the end of input

### ISSUE THREAD

**Issue by ClementNerma** [arijit79/minus#81]
Hi there!

I'm currently this crate for a log displaying system, and I'd like to have the ability to start the pager at the very end of the log's content. That way users see the last messages first, and can then scroll up to see the older ones.

I didn't find any option to set this behaviour in the crate, so would be it possible to implement it?

Thanks in advance for your help :)

**Comment by arijit79** [comment]
Yes there is surely a possibility to implement paging from bottom. 

But minus has always been a top to bottom paging library and hence it makes a lot of optimization for this case. 

For example, if the screen is not filled and new data comes in, minus will just modify the last few lines (maybe none, whatever it decides according to the situation it is in) and does not have redraw all the text that is present. This vastly reduces the number of lines that needs to be displayed on data appending.

Also if the screen is full, it formats all new data that comes and simply stores it in its buffer, without giving any concern to the display functions.

So yeah there are some open questions that need to be resolved before we can take the first steps

- Everytime when some bit of text is appended will that cause the entire display to redraw?Can we do some optimization here like previously?

- If the user has gone up a few lines then minus will keep that in view until the user doesn't press a movement key. If that is so then if the user goes  up and comes back down again, how will minus differentiate whether the user wants to stay on the current last line or scroll down with the upcoming data.

- What about static paging? Will we have a support for bottom-top pager for static paging as well since there are special optimization for this as well.

**I am actually really excited to see hoe many more use cases minus can handle with this landed.**

Now I am super busy right now. I am working on a small website for minus to host more guides and documentation, especially for new contributors. I am also researching on whether we could introduce `rayon` to use a large threadpool for fast concurrent optimization for different operations, also on improving the performance during movement and much more.
So if you want to help, you are more than welcome to open a PR on GitHub. Join our Discord or Matrix if you want need any help.

**Comment by ClementNerma** [comment]
I was mostly thinking about implementing this feature for the static pager exclusively. Implementing it for the dynamic pager would be a lot more complex, as you pointed out.

I'm currently very taken with my own projects, but when they are in a stable state I'll try to find the time to make a PR if I can :)

**Comment by arijit79** [comment]
Fine then.... I will be making changes in a draft PR as I manage to get time for this. You can also give up your your own code contributions or any suggestions that you feel.

**Comment by ClementNerma** [comment]
The way I think it could be implemented would be a method on the pager to go the last line.
So you first set up the pager and set its content (static), and then call a method that will drag the "cursor" to the very last line.
That way it should be pretty trivial to implement as the pager is just changing the active line number.
